library(vioplot)
par(mfrow=c(1,3))
setwd("/Users/joseph.walker/Desktop/OutlierFinal/SimulationOrthology/")
b = read.csv("orthology_SSLLs.txt",header=FALSE)
c = read.csv("Short_orthology_SSLLs.txt",header=FALSE)
d = read.csv("Short_short_orthology_SSLLs.txt",header=FALSE)
vioplot(d[,1],d[,2],d[,3],d[,4],d[,5],ylim=c(-0.5,0.15),main="0.1 subs/bp",ylab= "ΔSSLL",xlab="Gene")
vioplot(c[,1],c[,2],c[,3],c[,4],c[,5],ylim=c(-0.5,0.15),main="0.3 subs/bp",ylab= "ΔSSLL",xlab="Gene")
vioplot(b[,1],b[,2],b[,3],b[,4],b[,5],ylim=c(-0.5,0.15),main="0.6 subs/bp",ylab= "ΔSSLL",xlab="Gene")
