library(vioplot)
par(mfrow=c(1,3))
setwd("/Users/joseph.walker/Desktop/OutlierFinal/SimulationHeterotachy/")
b = read.csv("Short_short_heterotachy_SSLLs.txt",header=FALSE)
vioplot(b[,1],b[,2],b[,3],b[,4],b[,5],ylim=c(-0.5,0.2),main="Avg. SSLL Two-Topology Test",ylab= "ΔSSLL",xlab="Gene")
b = read.csv("Short_heterotachy_SSLLs.txt",header=FALSE)
vioplot(b[,1],b[,2],b[,3],b[,4],b[,5],ylim=c(-0.5,0.2),main="Avg. SSLL Two-Topology Test",ylab= "ΔSSLL",xlab="Gene")
b = read.csv("heterotachy_SSLLs.txt",header=FALSE)
vioplot(b[,1],b[,2],b[,3],b[,4],b[,5],ylim=c(-0.5,0.2),main="Avg. SSLL Two-Topology Test",ylab= "ΔSSLL",xlab="Gene")
